config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users

   root 'home#index'
   match "searchartist" => "home#search_artist", :as => "searchartist",via: [:get, :post]
   match "search_history" => "home#search_history", :as => "search_history",via: [:get, :post]

end

app/models/history.rb
class History < ActiveRecord::Base
belongs_to :user
end

app/models/lastfm.rb
require 'httparty'
class Lastfm
include HTTParty
  base_uri 'http://ws.audioscrobbler.com/2.0/'
  default_params :api_key => '7a158277d79505776149a311b51ebd2f', :format => "json"  #:api_key => Constants::LASTFM_API_KEY

   def get_artist_albums(searchartist)
 
     options = {:artist => searchartist, :method => "artist.getTopAlbums" }
     puts options.to_query  # log purpose
     response=self.class.get "/?#{options.to_query}", {} 
     result= JSON.parse(response.body)
    end


    def get_artist_search(searchartist)
 
     options = { :artist => searchartist,:method => "artist.search"}
     puts options.to_query
     response=self.class.get "/?#{options.to_query}", {} 
     result= JSON.parse(response.body)
 end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 has_many  :histories
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def search_history
        @id=current_user.id
       @user= User.find(@id)
        @histories= @user.histories
  end
  def search_artist
    @history= History.new
     @lastfm = Lastfm.new
     @artist_search = @lastfm.get_artist_search( params[:search])
     @artist = @artist_search["results"]["artistmatches"]["artist"][0]
     @albums = @lastfm.get_artist_albums(@artist["name"])
     @tracks = @lastfm.get_artist_top_tracks(@artist["name"])
     @similar_artists = @lastfm.get_similar_artists(@artist["name"])
    @history.search_term = @artist["name"]
    @history.user_id= current_user.id
    @history.save
    
     
     respond_to do |format|
        format.html  
        #format.json  { render :partial => "artistinfo", :locals => {@artistinfo => @artistinfo, :query => params[:search]} }
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/search_artist.html.erb
<%= link_to 'Back', root_path %>
Search Results
<% image_path= @artist["image"][0]["#text"] %>
 <h3><%= @artist["name"] %></h3>
 <%= image_tag image_path %> </br>


<h2> Similar artists </h2>
<% @similar_artists["similarartists"]["artist"].each do |sa| %>
 <%= sa["name"] %>
<% image_path = sa ["image"][0]["#text"] %>
<%= image_tag image_path %> </br>
<% end %>

<h2> Top Tracks </h2>
<% @tracks["toptracks"]["track"].each do |tr| %>
 <%= tr["name"] %> </br>
<% end %>
</br>






   
     

app/views/home/search_history.html.erb
<h3>Search History</h3> 
<%= link_to 'Back', root_path %>

<table>
  <thead>
    <tr>
      <th>Searched For </th>
     <th> Time </th>
 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.search_term %></td>
         <td><%= history.created_at %></td>
           
        
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', root_path %>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ArtistTask</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.username %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  <%= link_to 'Search History', search_history_url %> </br></br>


<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


<%= yield %>

</body>
</html>

app/views/shared/_top_tracks.html.erb
<% tracks["toptracks"]["track"].each do |tr| %>
 <%= tr["name"] %> </br>
<% end %>
<% else %>
NO Similar artists found
<% end %>